### ISSUE TITLE
Colaboración

### ISSUE THREAD

**Issue by Jalagarto** [BIMCV-CSUSP/BIMCV-COVID-19#17]
Hola. Soy especialista en Deep Learning especializado en procesamiento de imágenes. 

Probaré algo en cuanto tenga algo de tiempo. Hay algún tipo de premisa o algo que quisiérais comentar al respecto o simplemente creo una carpeta y me pongo a ello? Mi idea es probar un par de algoritmos y mostrar resultados visuales y métricos. Os iré preguntando cosas por aquí. 

Si tenéis otro canal de preferencia hacédmelo saber. Saludos!

**Comment by Jalagarto** [comment]
It doesn't let me push any added commits. I guess it's not open to everyone to commit, so I would work on my own version repository and let you know if I get some results I guess, unless you have any other suggestion

Find here [my repository version based on yours](https://github.com/Jalagarto/BIMCV-COVID-19_pytorch)

**Comment by maigva** [comment]
Gracias Javi por tu contribución, estate atento a los updates
