### ISSUE TITLE
Downscaled version of data set

### ISSUE THREAD

**Issue by RParedesPalacios** [BIMCV-CSUSP/BIMCV-COVID-19#2]
The dataset is too big I think that is an expensive ticket to start with this project. 

Taking a look to the code you propose an image working size of:

 y, x, in_channel = 724, 200, 1

that perhaps is not enough but I agree that it is ok for starting.

Therefore, could you please provide a just reduced version of the images?? 

A fast calc:: 30 K images x 724 x 200 x 1 = 4GB approx in 8 bits precision or 32 for float32.

In any case significantly lower than the 160G of zip file.

**Comment by maigva** [comment]
Thanks for great suggestion. Please review updates
https://github.com/BIMCV-CSUSP/BIMCV-COVID-19/blob/master/padchest-covid/README.md
Maria

**Comment by jaideep11061982** [comment]
@maigva  where are the labels for the files.
and are they bbx annotations or classification labels
