### ISSUE TITLE
Where is the segmentation?

### ISSUE THREAD

**Issue by qsyao** [BIMCV-CSUSP/BIMCV-COVID-19#31]
Thanks for your great work!
I can't find the segmentation Ground Truth and their corresponding nii.gz.
Thank you!

**Comment by maigva** [comment]
Hi qsyao
there is not segmentations in nii.gz format. In "bimcv_covid19_posi_head_iter1.tgz",  the 10 ROIs images from different series are in xml format, more concretly in derivatives folder.

For example "/derivatives/roi/sub-S03044/derivatives\roi\sub-S03044\ses-E06138\mod-rx\sub-S03044_ses-E06138_run-1_bp-chest_vp-ap_mod-cr_roi.xml"
