### ISSUE TITLE
Slow DataGenerator

### ISSUE THREAD

**Issue by RParedesPalacios** [BIMCV-CSUSP/BIMCV-COVID-19#6]
I observe that most of the time GPU is idle because CPU is reading images and doing DA (one-thread!). This is not good.

I think that you could provide different numpy with images just rescaled to different sizes (256x256), (512x512) for training, dev and test and we can load all into memory (i think that with a 32Gb machine it fits) and then use a standard Keras data augmentation that use all the CPU threads. I think we can scale up x4 - x8 training speed at least.

**Comment by maigva** [comment]
Thanks
